server {
    listen 8088;
    server_name localhost 127.0.0.1;

    root /Volumes/Extend/coding-workspace/front-end/openapi-readme/docs/.vitepress/dist;
    index index.html;

    location /api/openapi/v1/ {
        proxy_pass https://openapi-au.pylontechcloud.com/api/openapi/v1/;
        proxy_ssl_server_name on;
        proxy_set_header Host openapi-au.pylontechcloud.com;
        proxy_set_header Authorization $http_authorization;
    }

    location / {
        try_files $uri $uri.html $uri/ /404.html;
    }
}
